language: python
python:
  - '3.6'

install:
  - make install-requirements
  - mkdir .aws
  - echo -e '[profile default]\noutput = table\nregion = eu-central-1' > .aws/config
  - echo -e '[default]\naws_access_key_id = key\naws_secret_access_key = key' > .aws/credentials

script:
  - make test
  - make build
  - make test-container
