sudo: required

language: python
python:
  - '3.6'

services:
  - docker

install:
  - make install-requirements
  - make build

script:
  - make test
  - docker run --rm /bin/sh -c "cd functions && xawscf process"
