sudo: required

language: python
python:
  - '3.6'

services:
  - docker

git:
  depth: 3

install:
  - make install-requirements

script:
  - make test && make lint && ./check-examples.sh && ./travis-check-container.sh
